name: GitHub-Profile-3D-Contrib

on:
  schedule: # Define a execução diária do workflow
    - cron: "0 18 * * *"  # Esse horário está definido para 18:00 UTC; ajuste conforme necessário
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso; veja as instruções abaixo
          USERNAME: ${{ github.repository_owner }}  # Nome de usuário do GitHub
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
